#!/usr/bin/env python3
"""Erase every reference to another repository, branch, commit or artifact.

The source workbooks were generated by tooling that lives elsewhere and recorded
their own build provenance. That provenance is meaningful in its originating
project and meaningless here, so it is removed: the repository and branch, the
build commit, the export and verify scripts, the exported package names, and the
register files the workflow IDs were looked up in.

File names the ESTATE itself owns are not touched - the definition schema name,
the schema files a request contract declares, and the names a flow builds at run
time to write into SharePoint. Those are data, not provenance.
"""
import os, re
import pathlib
import signal
signal.signal(signal.SIGPIPE, signal.SIG_DFL)  # writing into `| head` is not an error
import openpyxl

WB = os.environ.get('ESTATE_WORKBOOK',
    str(pathlib.Path(__file__).resolve().parent.parent / 'DGO_Unified_Endpoint_Estate_Merged.xlsx'))
GONE = '(reference removed)'

# Paths that only exist inside the originating project.
PATH = re.compile(r'\b(?:docs|scripts)/[A-Za-z0-9._/-]+')
COMMIT = re.compile(r'\b[0-9a-f]{40}\b')
BRANCH = re.compile(r'\bbranch\s+claude/[A-Za-z0-9._-]+')
CLAUDE_BRANCH = re.compile(r'claude/[A-Za-z0-9._-]+')

# Prose that points at the originating repository as a place.
PROSE = [
    ('Signatures published from this repository', 'Signatures published from the source system'),
    ('Nothing in the repository claims', 'Nothing in the source registers claims'),
    ('nothing in the repository claims', 'nothing in the source registers claims'),
    ('already exported into the repository', 'already exported into the source system'),
]

# Whole columns of per-row build provenance, addressed by header name so no
# pattern has to recognise an exported package by its shape.
COLUMN_BLANK = {('03 Flows', 'Exported by'), ('03 Flows', 'Source package')}

# Register files the workflow IDs were looked up in. The register is foreign; the
# endpoint key in brackets after it is estate data, so only the name goes.
REGISTER = re.compile(r'\b[A-Za-z0-9_-]+-(?:register|workflow-ids)\.json\b')
# Export and verify tooling, named in prose.
TOOLING = re.compile(r'\b[A-Za-z0-9_.-]+\.(?:ps1|py)\b')

# Cells rewritten whole, because the reference is woven into the sentence.
CELL_TEXT = {
    ('01 Cover', 'A2'): ('Every endpoint and every flow captured from the Power Platform '
                         'environment, with all configured detail, read from the exported '
                         'flow packages.'),
    ('01 Cover', 'B7'): 'flow definitions exported from the environment',
}

# Cells whose whole value is build provenance for the originating project.
WHOLE_CELL = {('01 Cover', 'B5'), ('01 Cover', 'B6'), ('01 Cover', 'B8'),
              ('HC 00 README', 'B43'), ('HC 00 README', 'B45')}

wb = openpyxl.load_workbook(WB, data_only=False)
changes = []


def header_of(ws, col):
    """These sheets put their header on row 4; anything else has no column rules."""
    v = ws.cell(row=4, column=col).value
    return str(v).strip() if v is not None else ''


for ws in wb.worksheets:
    for row in ws.iter_rows():
        for c in row:
            if not isinstance(c.value, str):
                continue
            before = c.value
            v = before

            if c.row > 4 and (ws.title, header_of(ws, c.column)) in COLUMN_BLANK:
                v = GONE
            elif (ws.title, c.coordinate) in CELL_TEXT:
                v = CELL_TEXT[(ws.title, c.coordinate)]
            elif (ws.title, c.coordinate) in WHOLE_CELL:
                v = GONE
            else:
                for a, b in PROSE:
                    v = v.replace(a, b)
                # Drop the directory first, so removing a file name below cannot
                # leave a dangling "scripts/" behind.
                v = PATH.sub(lambda m: m.group(0).rsplit('/', 1)[-1], v)
                v = REGISTER.sub('endpoint register', v)
                v = TOOLING.sub(GONE, v)
                v = COMMIT.sub(GONE, v)
                v = BRANCH.sub(GONE, v)
                v = CLAUDE_BRANCH.sub(GONE, v)

            if v != before:
                c.value = v
                changes.append((ws.title, c.coordinate, before[:70], v[:70]))

# Relabel the two provenance rows so the sheet still reads correctly.
cov = wb['01 Cover']
cov['A5'], cov['A6'] = 'Built from', 'Source project'
wb.save(WB)

print(f'cells changed: {len(changes)}')
seen = set()
for s, coord, b, a in changes:
    key = (s, b[:40])
    if key in seen:
        continue
    seen.add(key)
    print(f'  {s:22s} {coord:7s} {b!r}\n  {"":22s} {"":7s} -> {a!r}')
