import { hydrateGovernance, executeOwnedAction } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { head, esc, toast, confirmAction, badge, mdBack, mdSwitch, resetDetailScroll, statRow, actionPreview} from '../core/ui.js';
import { UIState } from '../core/ui-state.js';
import { ReceiptLedger } from '../core/receipt-ledger.js';
import { OfflineActionQueue } from '../core/offline-action-queue.js';
import { DeepLinkResolver } from '../core/deeplink-resolver.js';
import { requestSync } from '../core/data-loader.js';
import { selectTaskForAcknowledgement, submitAcknowledgement, buildAcknowledgementPayload, validateAcknowledgementPayload, retryQueuedAcknowledgements, exportAcknowledgementReceipts, acknowledgementHealth, findAcknowledgementTask, resolveAcknowledgementActor } from '../core/acknowledgement-service.js';

export async function mount(el){ hydrateGovernance(); render(el); }
function slaCompliance(tasks) { const withDue = tasks.filter(t => t.ack); if (!withDue.length) return null; const onTime = withDue.filter(t => t.acknowledged && (!t.ackedAt || new Date(t.ackedAt).getTime() <= new Date(t.ack + 'T23:59:59').getTime())); return Math.round((onTime.length / withDue.length) * 100); }
function ageDays(t) { const from = t.created || t.start || t.createdAt; if (!from) return null; return Math.max(0, Math.floor((Date.now() - new Date(from).getTime()) / 86400000)); }
function downloadText(filename, text, type='application/json'){ const blob=new Blob([text],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function copyText(text,label='Text'){ navigator.clipboard?.writeText(text).then(()=>toast(label+' copied','success')).catch(()=>downloadText(label.replace(/\s+/g,'-').toLowerCase()+'.txt',text,'text/plain')); }
async function buildPreview(task, form={}){ try{return await buildAcknowledgementPayload(task,{source:'acknowledgment-preview', form});}catch(e){return {error:e.message};} }
function actorFormHtml(){ const a=resolveAcknowledgementActor(); return `<section class="panel"><div class="eyebrow panel-eyebrow">Who is acknowledging</div><div class="grid" data-ack-user-form><label>Name<input name="actorName" value="${esc(a.name)}" required></label><label>Email<input name="actorEmail" type="email" value="${esc(a.email)}" required></label><label>Persona / Role<input name="persona" value="${esc(a.persona)}"></label><label>Department / Unit<input name="department" value="${esc(a.department)}"></label></div><p class="meta">Taken from ${esc(a.source)}. These details are recorded with the acknowledgement and kept on its receipt.</p></section>`; }
function readActorForm(root){ const box=root.querySelector('[data-ack-user-form]'); if(!box) return {}; return Object.fromEntries([...box.querySelectorAll('input,select,textarea')].map(x=>[x.name,x.value])); }
function ackConvergencePanel(){ const ctx=State.get().deepLinkContext||{}, h=acknowledgementHealth(); return `<section class="panel"><h2>Receipts and linked task</h2><div class="action-row"><span>Task opened from a link</span><b>${esc(ctx.taskId||ctx.referenceId||'None')}</b></div><div class="action-row"><span>Receipts</span><b>${h.receipts.count}</b></div><div class="action-row"><span>Waiting to be sent</span><b>${h.queue.count}</b></div><div class="action-row"><span>Latest receipt</span><b>${esc(h.receipts.latest||'—')}</b></div><div class="toolbar"><button class="btn" data-retry-ack>Send acknowledgements that are waiting</button><button class="btn ghost" data-export-receipts-csv>Export receipts to spreadsheet</button><button class="btn ghost" data-export-receipts>Export receipts (JSON)</button><button class="btn ghost" data-copy-deeplink>Copy this task's link details</button><button class="btn ghost" data-refresh-data>Load latest records</button></div></section>`; }
function findSelected(tasks,u){ const s=State.get(), ctx=s.deepLinkContext||{}; return selectTaskForAcknowledgement(s,u.selected||ctx.taskId||ctx.referenceId||s.selectedId) || tasks[0] || null; }
function taskRows(tasks, sel){ return tasks.map(t=>{ const age=ageDays(t), active=sel&&String(sel.id)===String(t.id); return `<tr class="row-link ${active?'row-active':''}" data-id="${esc(t.id)}"><td><div>${esc(t.title)}</div><div class="meta">${esc(t.referenceId || t.id)}</div></td><td>${age == null ? '—' : badge(age + 'd', !t.acknowledged && age >= 2 ? 'danger' : '')}</td><td>${badge(t.acknowledged ? 'Acknowledged' : 'Pending', t.acknowledged ? 'ok' : '')}</td></tr>`; }).join(''); }
function render(el) {
  const s = State.get(); const tasks = s.tracking || []; const u = UIState.get('acknowledgment', { selected: null, md: 'list' }); const ctx=s.deepLinkContext||{};
  const sel = findSelected(tasks,u); if(sel && (!u.selected || (ctx.taskId && String(u.selected)!==String(sel.id)))) UIState.set('acknowledgment',{selected:sel.id,md:ctx.taskId||ctx.referenceId?'detail':u.md});
  const pending = tasks.filter(t => !t.acknowledged); const acked = tasks.filter(t => t.acknowledged); const sla = slaCompliance(tasks); const missingCtx=(ctx.taskId||ctx.referenceId) && !findAcknowledgementTask(s,ctx.taskId||ctx.referenceId);
  el.innerHTML = `<div class="workspace">${head('Acknowledgment Queue', 'Confirm receipt of the tasks routed to you, and keep the record of who confirmed what.')}
    ${statRow([['Pending Acknowledgements', pending.length], ['Acknowledged Tasks', acked.length], ['SLA Compliance', sla == null ? '—' : sla + '%'], ['Total', tasks.length]])}
    ${missingCtx?`<section class="panel"><div class="notify-banner error show"><b>The task this link points to has not loaded</b><p>The link names ${esc(ctx.taskId||ctx.referenceId)}, but that task is not among the records loaded on this device. Load the latest records, or find it in Lookup &amp; Direct Action.</p></div></section>`:''}
    ${ackConvergencePanel()}
    <div class="split" ${mdSwitch(sel?UIState.get('acknowledgment').md:'list')}><div class="panel">${tasks.length ? `<div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th>Task</th><th class="col-narrow">Ageing</th><th class="col-narrow">Status</th></tr></thead><tbody>${taskRows(tasks,sel)}</tbody></table></div>` : '<div class="empty dgo-empty"><h2 class="dgo-empty__title">No tasks to acknowledge</h2><p>A task appears here once it has been assigned to you. Nothing has been loaded from the registry in this session.</p><p><button type="button" class="btn" data-refresh-data>Load latest records</button></p></div>'}</div>
    <div class="detail-col panel-stack">${sel ? detail(sel) : '<section class="panel"><div class="empty dgo-empty"><h2 class="dgo-empty__title">No task selected</h2><p>Choose a task from the queue to read it and confirm receipt.</p></div></section>'}</div></div></div>`;
  bind(el, sel);
}
function bind(el, sel){
  el.querySelectorAll('tbody tr').forEach(tr => tr.onclick = () => { UIState.set('acknowledgment', { selected: tr.dataset.id, md: 'detail' }); render(el); resetDetailScroll(el); });
  el.querySelector('[data-md-back]')?.addEventListener('click', () => { UIState.set('acknowledgment', { md: 'list' }); render(el); });
  el.querySelectorAll('[data-refresh-data]').forEach(b=>b.addEventListener('click',async()=>{ b.disabled=true; try{ await requestSync({source:'acknowledgment',mode:'deeplink-refresh'}); toast('Records reloaded from the registry','success'); render(el); }catch{ toast('The registry could not be reached, so nothing was reloaded. Try again, or contact IT support if it keeps failing.','error'); }finally{ b.disabled=false; } }));
  el.querySelector('[data-retry-ack]')?.addEventListener('click',async e=>{ e.currentTarget.disabled=true; try{ const r=await retryQueuedAcknowledgements(); toast(`${r.ok} acknowledgement(s) sent, ${r.fail} still waiting`, r.fail?'error':'success'); render(el); }catch(x){ toast(x.message,'error'); }finally{ e.currentTarget.disabled=false; } });
  el.querySelector('[data-export-receipts]')?.addEventListener('click',()=>downloadText('dgo-acknowledgement-receipts.json', exportAcknowledgementReceipts('json')));
  el.querySelector('[data-export-receipts-csv]')?.addEventListener('click',()=>downloadText('dgo-acknowledgement-receipts.csv', exportAcknowledgementReceipts('csv'), 'text/csv'));
  el.querySelector('[data-copy-deeplink]')?.addEventListener('click',()=>copyText(JSON.stringify(State.get().deepLinkContext||{},null,2),'Link details'));
  const ackBtn = el.querySelector('[data-ack]'); if (ackBtn) ackBtn.onclick = async () => {
    const actorForm=readActorForm(el); const preview=await buildPreview(sel, actorForm); const validation=validateAcknowledgementPayload(preview); if(validation.length) return toast(validation.join('; '),'error');
    if (!await confirmAction({ title: 'Confirm receipt of this task', body: `<p><b>${esc(sel.title)}</b></p><p>${esc(sel.referenceId || sel.id)}</p><p>This records that you have received the task. A notice goes to the assigned officer, copied to Registry.</p>${actionPreview(preview)}`, confirmText:'Acknowledge receipt', cancelText:'Cancel' })) return;
    ackBtn.disabled=true;
    try{ const result=await executeOwnedAction('acknowledgment', 'acknowledge', () => submitAcknowledgement(sel,{source:'acknowledgment', form:actorForm}), { ref: sel.referenceId || sel.id, meta:{deeplink:!!State.get().deepLinkContext?.taskId} }); toast(result.status==='queued'?'Acknowledgment recorded on this device — it will reach the registry when the connection returns':'Acknowledgment recorded and sent to the registry', result.status==='queued'?'error':'success'); render(el); }
    // No toast here. This catch used to repeat the raw `e.message` the governance layer had
    // already put on screen — two toasts, both written for a developer. The governance layer
    // names the action and what it means for the record; there is nothing truer to add about
    // an acknowledgment that failed, so it speaks alone and this only restores the screen.
    catch{ render(el); }
    finally{ ackBtn.disabled=false; }
  };
  el.querySelector('[data-remind]')?.addEventListener('click', async () => { if (!await confirmAction({ title: 'Remind the assignee to acknowledge', body: `<p><b>${esc(sel.title)}</b></p><p>${esc(sel.assignedTo || 'The assignee')} will be reminded to confirm receipt of this task.</p>` })) return; await executeOwnedAction('acknowledgment','remind-assignee',()=>{ const s=State.get(); State.patch({notifications:[{id:crypto.randomUUID(),at:new Date().toISOString(),taskId:sel.id,referenceId:sel.referenceId||'',title:`Acknowledgment reminder: ${sel.title}`,assignedTo:sel.assignedTo||''},...(s.notifications||[])]},{module:'acknowledgment',action:'ack:remind',ref:sel.referenceId||sel.id});},{ref:sel.referenceId||sel.id}); toast('Reminder recorded for '+(sel.assignedTo||'the assignee'),'success'); render(el); });
  el.querySelector('[data-track]')?.addEventListener('click',()=>{ State.patch({selectedId:sel.id}); location.hash='#/response-tracking'; });
  el.querySelector('[data-respond]')?.addEventListener('click',()=>{ State.patch({selectedId:sel.id,deepLinkContext:{...(State.get().deepLinkContext||{}),taskId:sel.id,mode:'respond'}}); location.hash='#/orchestrator'; });
  el.querySelector('[data-reassign]')?.addEventListener('click',()=>{ State.patch({selectedId:sel.id,deepLinkContext:{...(State.get().deepLinkContext||{}),taskId:sel.id,mode:'reassign'}}); location.hash='#/single-assignment'; });
  el.querySelector('[data-attachments]')?.addEventListener('click',()=>{ const links=[...(Array.isArray(sel.attachments)?sel.attachments:[]), sel.attachmentLink||sel.AttachmentLink].filter(Boolean); if(!links.length) return toast('This task has no attachments','error'); window.open(typeof links[0]==='string'?links[0]:(links[0].AbsoluteUri||links[0].absoluteUri||links[0].url||''),'_blank','noopener,noreferrer'); });
  el.querySelector('[data-copy-payload]')?.addEventListener('click',async()=>copyText(JSON.stringify(await buildPreview(sel, readActorForm(el)),null,2),'Record details'));
  el.querySelector('[data-parse-url]')?.addEventListener('click',()=>{ const r=DeepLinkResolver.parse(location.href); toast(r.route?`This page's link opens ${r.route}`:"This page's address does not point at a task", r.route?'success':'error'); });
}
function detail(t) {
  const age = ageDays(t); const receipts=ReceiptLedger.byRef(t.referenceId||t.id).concat(ReceiptLedger.byRef(t.id)).slice(0,8);
  return `${mdBack('Back to queue')}<section class="panel"><div class="eyebrow panel-eyebrow">Who may acknowledge</div><p class="meta">Only the assigned officer may confirm receipt. Assigned to: <b>${esc(t.assignedTo||t.AssignedTo||'—')}</b></p></section><section class="panel"><div class="eyebrow panel-eyebrow">Acknowledgment Notice</div><div class="meta">${esc(t.referenceId || t.id)} · ${badge(t.acknowledged ? 'Acknowledged' : 'Pending', t.acknowledged ? 'ok' : '')}${age != null ? ' · ' + badge('Waiting ' + age + 'd', !t.acknowledged && age >= 2 ? 'danger' : '') : ''}</div><h2>${esc(t.title)}</h2><p class="meta">Assigned to: ${esc(t.assignedTo||'Unassigned')} · Acknowledgement due: ${esc(t.ack||'—')}</p><p>You are being asked to confirm receipt of: ${esc(t.title)}</p></section>
    ${actorFormHtml()}<section class="panel"><div class="eyebrow panel-eyebrow">What happens on acknowledgement</div><p class="meta">A notice is sent to the assigned officer with a copy to Registry, and a receipt is added below.</p></section><section class="panel"><div class="eyebrow panel-eyebrow">Receipt Actions</div><div class="form-row">${t.acknowledged ? '<span class="pill ok">Receipt confirmed</span>' : '<button class="btn" data-ack>Acknowledge Receipt</button><button class="btn ghost" data-remind>Send Reminder</button>'}<button class="btn ghost" data-track>Track History</button><button class="btn ghost" data-respond>Respond</button><button class="btn ghost" data-reassign>Reassign or Forward</button><button class="btn ghost" data-attachments>Attachments</button><button class="btn ghost" data-copy-payload>Copy record details</button><button class="btn ghost" data-parse-url>Check this page's link</button></div></section>
    <section class="panel"><div class="eyebrow panel-eyebrow">Receipt Ledger</div>${receipts.length?receipts.map(r=>`<div class="action-row"><span><b>${esc(r.status)}</b><small>${esc(r.createdAt||r.at||'')} · ${esc(r.receiptId)}</small></span>${badge(r.source||'ack')}</div>`).join(''):'<p class="meta">No receipts for this task yet.</p>'}</section>`;
}
