import { hydrateGovernance, executeOwnedAction } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { UIState } from '../core/ui-state.js';
import { head, kpis, esc, toast, confirmAction, badge, mdBack, mdSwitch, resetDetailScroll, fmtDateTime, emptyFor, loadFlags, refCode} from '../core/ui.js';
import { capRows, RenderBudget } from '../core/render-budget.js';
import { CorrespondenceEmailService as Mail } from '../core/correspondence-email-service.js';

export async function mount(el){ hydrateGovernance(); render(el); }
const U=()=>UIState.get('correspondence-email',{tab:'sources',selected:'',md:'list',template:'official-correspondence'});
function tone(x){ return x.status==='sent'?'ok':x.status==='queued'?'warn':x.status==='archived'?'info':''; }
function render(el){
  const s=State.get(), u=U(), sources=Mail.sourceCorrespondences(s), rows=s.correspondenceEmails||[], stats=Mail.stats(s), selected=rows.find(x=>x.id===u.selected)||null;
  /* I-21 — the four counts were pills that carried their own label inside the text ("Drafts:
     3"), so the numbers could not be read at a glance and did not line up with the metric band
     every other workspace uses. They are counts, so they belong in kpis(): label above, number
     below, nothing else. The sentence that says what this desk is for is a caption underneath,
     not a fifth pill. */
  el.innerHTML=`<div class="workspace">${head('Correspondence Email Desk','Write, check and send official letters by email, and keep a record of everything that went out.')}
  ${kpis([['Drafts',stats.draft],['Waiting to go out',stats.queued],['Sent',stats.sent],['All emails',stats.total]])}
  <section class="panel"><div class="eyebrow panel-eyebrow">Official email correspondence register</div><p>This desk sends real letters out of the office by email. It does not notify anyone about tasks — that happens on the task screens.</p></section>
  <div class="toolbar"><button class="btn ${u.tab==='sources'?'':'ghost'}" data-tab="sources">Source Correspondence</button><button class="btn ${u.tab==='drafts'?'':'ghost'}" data-tab="drafts">Drafts / Outbox</button><button class="btn ${u.tab==='register'?'':'ghost'}" data-tab="register">Sent Register</button><button class="btn ${u.tab==='templates'?'':'ghost'}" data-tab="templates">Templates</button></div>
  ${u.tab==='templates'?templates():u.tab==='register'?register(rows):workspace(s,u,sources,rows,selected)}</div>`;
  bind(el);
}
function templates(){ return `<section class="panel"><h2>Official templates</h2><div class="dashboard-grid">${Mail.templates().map(t=>`<article class="panel"><div class="eyebrow">${esc(t.category)}</div><h3>${esc(t.label)}</h3><p class="meta">A ${esc(t.tone)} letter, laid out on the official letterhead.</p><span class="pill">${(t.required||[]).length} fields you must fill in</span></article>`).join('')}</div></section>`; }
/* I-13 — the register said "No sent email correspondences yet" and stopped. The register is
   not filtered, so it has two honest arms: nothing has been sent, or nothing loaded. */
function register(rows){ const sent=rows.filter(x=>x.status==='sent'); return `<section class="panel"><h2>Everything sent from this desk</h2>${sent.length?`<div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th>Reference</th><th>Subject</th><th>Recipient</th><th>Template</th><th>Sent</th><th>By</th></tr></thead><tbody>${sent.map(x=>`<tr><td>${esc(x.referenceId)}</td><td>${esc(x.subjectLine||x.subject)}</td><td>${esc(x.recipientEmail)}</td><td>${esc(x.templateId)}</td><td>${esc(fmtDateTime(x.sentAt||''))}</td><td>${esc(x.sentBy||'')}</td></tr>`).join('')}</tbody></table></div>`:emptyFor({...loadFlags(State.get().runtime),noun:'sent emails',createLabel:'Open Drafts / Outbox',createAttr:'data-open-drafts'})}</section>`; }
function workspace(s,u,sources,rows,selected){ const list=u.tab==='sources'?sources:rows.filter(x=>x.status!=='archived'); return `<div class="split" ${mdSwitch(u.md)}><div class="list-col panel">${u.tab==='sources'?sourceList(list,s):draftList(list,selected,s)}</div><div class="detail-col panel-stack">${u.tab==='sources'?composer(sources.find(x=>String(x.id)===String(u.selected))||sources[0]||null,u):selected?detail(selected):`<section class="panel"><div class="empty dgo-empty"><h2 class="dgo-empty__title">No email open</h2><p>Choose an email on the left to read it, send it or archive it. Nothing is open, so there is nothing to show.</p></div></section>`}</div></div>`; }
/* I-13 — both lists stated a fact. Neither is filtered (the tabs switch between two different
   lists rather than narrowing one), so each has two honest arms: genuinely nothing here, or
   nothing loaded. loadFlags() supplies the second from lastLoad.ok. */
function sourceList(list,s){ return list.length?capRows(list,RenderBudget.listRows).map(r=>`<div class="list-item" data-source="${esc(r.id)}"><div class="meta">${esc(r.kind)} · ${esc(r.referenceId||'No reference')} ${badge(r.classification||'Official')}</div><h4>${esc(r.subject||'Untitled correspondence')}</h4><div class="meta">Suggested recipient: ${esc(r.recipientEmail||r.recipientName||'none on file')}</div></div>`).join(''):emptyFor({...loadFlags(s?.runtime),noun:'letters to reply to'}); }
function draftList(list,selected,s){ return list.length?capRows(list,RenderBudget.listRows).map(x=>`<div class="list-item ${selected&&selected.id===x.id?'active':''}" data-draft="${esc(x.id)}"><div class="meta">${badge(x.status,tone(x))} ${esc(x.referenceId||'—')}</div><h4>${esc(x.subjectLine||x.subject)}</h4><div class="meta">To: ${esc(x.recipientEmail||'—')} · ${esc(fmtDateTime(x.updatedAt||x.createdAt||''))}</div></div>`).join(''):emptyFor({...loadFlags(s?.runtime),noun:'drafts',createLabel:'Start one from a letter',createAttr:'data-open-sources'}); }
function composer(src,u){
  if(!src)return `<section class="panel"><div class="empty dgo-empty"><h2 class="dgo-empty__title">No letter chosen</h2><p>Choose a letter on the left and its details are carried into a draft reply here.</p></div></section>`;
  const draft={templateId:u.template,sourceId:src.id,sourceKind:src.kind,referenceId:src.referenceId,subject:src.subject,recipientName:src.recipientName,recipientEmail:src.recipientEmail,classification:src.classification,attachmentSummary:(src.attachmentLinks||[]).join('; ')};
  const rendered=Mail.render(draft,src);
  return `${mdBack('Back to source correspondences')}<form class="panel grid" data-compose><input type="hidden" name="sourceId" value="${esc(src.id)}"><input type="hidden" name="sourceKind" value="${esc(src.kind)}"><div class="eyebrow panel-eyebrow wide">Compose outgoing correspondence email</div><label>Template<select name="templateId">${Mail.templateOptions(u.template)}</select></label><label>Reference<input name="referenceId" value="${esc(rendered.ctx.referenceId)}"></label><label class="wide">Subject<input name="subject" value="${esc(rendered.ctx.subject)}" required></label><label>Recipient name<input name="recipientName" value="${esc(rendered.ctx.recipientName)}"></label><label>Recipient email<input name="recipientEmail" type="email" value="${esc(rendered.ctx.recipientEmail)}" required></label><label>CC<input name="cc" placeholder="email1; email2"></label><label>BCC<input name="bcc"></label><label>Classification<select name="classification"><option>Official</option><option>Confidential</option><option>Restricted</option></select></label><label>Priority<select name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select></label><label>Due / response date<input name="dueDate" type="date"></label><label class="wide">Action required / instruction<input name="actionRequired"></label><label class="wide">Attachment reference(s)<input name="attachmentSummary" value="${esc(rendered.ctx.attachmentSummary)}"></label><label class="wide">Correspondence body<textarea name="body" rows="6" required>${esc(rendered.ctx.body)}</textarea></label><label>Signatory name<input name="signatoryName" value="${esc(rendered.ctx.signatoryName)}"></label><label>Signatory title<input name="signatoryTitle" value="${esc(rendered.ctx.signatoryTitle)}"></label><div class="wide form-row"><button class="btn">Save draft</button></div></form><section class="panel"><details open><summary>How this will look to the recipient</summary><div class="email-frame"><iframe title="Preview of the email as the recipient will see it" sandbox="" srcdoc="${esc(rendered.html)}"></iframe></div></details></section>`;
}
function detail(x){ return `${mdBack('Back to outbox')}<section class="panel"><div class="eyebrow panel-eyebrow">Correspondence email record</div><div class="status-strip">${badge(x.status,tone(x))} ${badge(x.classification)} ${badge(x.priority)}</div><h2>${esc(x.subjectLine||x.subject)}</h2><dl class="detail-grid"><dt>Reference</dt><dd>${refCode(x.referenceId)}</dd><dt>To</dt><dd>${esc(x.recipientEmail)}</dd><dt>Template</dt><dd>${esc(x.templateId)}</dd><dt>Updated</dt><dd>${esc(fmtDateTime(x.updatedAt||''))}</dd>${x.sentAt?`<dt>Sent</dt><dd>${esc(fmtDateTime(x.sentAt))}</dd>`:''}${x.lastError?`<dt>Why it did not go out</dt><dd>${esc(x.lastError)}</dd>`:''}</dl><div class="form-row">${x.status!=='sent'?'<button class="btn" data-send>Send this email</button>':''}<button class="btn ghost" data-duplicate>Duplicate</button><button class="btn ghost" data-archive>Archive</button></div></section><section class="panel"><details open><summary>How this will look to the recipient</summary><div class="email-frame"><iframe title="Preview of the email as the recipient will see it" sandbox="" srcdoc="${esc(x.html)}"></iframe></div></details></section><section class="panel"><details><summary>Plain-text version, for recipients whose mail cannot show the letterhead</summary><pre class="preview-box">${esc(x.plain||'')}</pre></details></section>`; }
function bind(el){
  el.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{tab:b.dataset.tab,selected:'',md:'list'});render(el)});
  el.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{selected:b.dataset.source,md:'detail'});render(el);resetDetailScroll(el)});
  el.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{selected:b.dataset.draft,md:'detail'});render(el);resetDetailScroll(el)});
  el.querySelector('[data-md-back]')?.addEventListener('click',()=>{UIState.set('correspondence-email',{md:'list'});render(el)});
  /* The arms of the I-13 contract, wired. Each empty state offers one thing to do and these
     are what make it real: go to the list that can start a draft, or ask the registry again. */
  el.querySelectorAll('[data-open-sources]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{tab:'sources',selected:'',md:'list'});render(el)});
  el.querySelectorAll('[data-open-drafts]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{tab:'drafts',selected:'',md:'list'});render(el)});
  el.querySelectorAll('[data-retry-load]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const {requestSync}=await import('../core/data-loader.js');await requestSync({source:'correspondence-email',mode:'refresh'});toast('Reloaded from the registry','success')}catch{toast('The registry could not be reached — nothing was reloaded','error')}finally{b.disabled=false}render(el)});
  const f=el.querySelector('[data-compose]'); if(f){ f.templateId.onchange=()=>{UIState.set('correspondence-email',{template:f.templateId.value});render(el)}; f.onsubmit=async e=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(f)); const src=Mail.sourceCorrespondences().find(x=>String(x.id)===String(d.sourceId)); const errs=Mail.validate(d); if(errs.length)return toast(errs.join('; '),'error'); await executeOwnedAction('correspondence-email','create-correspondence-email-draft',()=>Mail.saveDraft(d,src),{ref:d.referenceId}); toast('Draft saved — it is in Drafts / Outbox and has not been sent','success'); UIState.set('correspondence-email',{tab:'drafts',selected:'',md:'list'}); render(el); }; }
  el.querySelector('[data-send]')?.addEventListener('click',async()=>{ const row=(State.get().correspondenceEmails||[]).find(x=>x.id===UIState.get('correspondence-email').selected); if(!row)return; /* I-07 — the audit's own example of the finding is a dialog that names a backend at the
   moment of decision. "This sends an outward correspondence via the configured EMAIL
   endpoint." is replaced by what actually happens: one letter leaves the office, to a named
   address, under this reference, and it cannot be recalled. */
if(!await confirmAction({title:'Send this letter now',body:`<p><b>${esc(row.subjectLine)}</b></p><p>It goes to <b>${esc(row.recipientEmail)}</b> as an official letter from this office, under reference ${esc(row.referenceId||'—')}.</p><p class="meta">Once it is sent it cannot be recalled. A copy is kept in the sent register with your name and the time.</p>`,confirmText:'Send it',cancelText:'Not yet'}))return; /* `notify:false` — "nothing was changed" would be wrong here and this screen knows it: the
   draft is still in the outbox and will go out by itself when the connection returns, so the
   operator has nothing to redo. That is worth more than the generic failure line. */
try{ await executeOwnedAction('correspondence-email','send-correspondence-email',()=>Mail.sendDraft(row),{ref:row.referenceId,notify:false}); toast('Letter sent — a copy is in the sent register','success'); }catch(e){ toast('It could not be sent just now — it stays in the outbox and goes out when the connection is back','error'); } render(el); });
  el.querySelector('[data-duplicate]')?.addEventListener('click',async()=>{ const row=(State.get().correspondenceEmails||[]).find(x=>x.id===UIState.get('correspondence-email').selected); if(!row)return; await executeOwnedAction('correspondence-email','duplicate-correspondence-email',()=>Mail.duplicate(row),{ref:row.referenceId}); toast('Draft duplicated','success'); render(el); });
  el.querySelector('[data-archive]')?.addEventListener('click',async()=>{ const row=(State.get().correspondenceEmails||[]).find(x=>x.id===UIState.get('correspondence-email').selected); if(!row)return; if(!await confirmAction({title:'Archive this email',body:`<p>${esc(row.subjectLine)}</p><p class="meta">It leaves the outbox and is kept on file. It is not sent, and the recipient is not told anything.</p>`,confirmText:'Archive it',cancelText:'Cancel'}))return; await executeOwnedAction('correspondence-email','archive-correspondence-email',()=>Mail.archive(row),{ref:row.referenceId}); toast('Archived — it is out of the outbox and was not sent','success'); UIState.set('correspondence-email',{selected:'',md:'list'}); render(el); });
}
