export const ActionRouting = Object.freeze({
  schema: "dgo-action-routing/v1",
  actions: [
  {
    "id": "fetch-docs",
    "label": "Fetch Documents / Activities",
    "sourceModule": "activities",
    "ownerModule": "activities",
    "actionType": "endpoint-action",
    "navigateTo": "activities",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:docs-fetched",
    "backendContract": "GET_DOCS",
    "postSuccess": "activities",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "filter-documents",
    "label": "Filter Documents",
    "sourceModule": "activities",
    "ownerModule": "activities",
    "actionType": "local-state",
    "navigateTo": "activities",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "activities",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "open-document-detail",
    "label": "Open Document Detail",
    "sourceModule": "activities",
    "ownerModule": "lookup",
    "actionType": "open-detail",
    "navigateTo": "lookup",
    "openAs": "detail-pane",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "lookup",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "flag-document",
    "label": "Flag Document",
    "sourceModule": "activities",
    "ownerModule": "activities",
    "actionType": "governed-action",
    "navigateTo": "lookup",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:document-flagged",
    "backendContract": "DYNAMIC_ACTIONS.optional",
    "postSuccess": "lookup",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "single-assign-document",
    "label": "Single Assign Document",
    "sourceModule": "activities",
    "ownerModule": "single-assignment",
    "actionType": "navigate",
    "navigateTo": "single-assignment",
    "openAs": "full-route",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "single-assignment",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "bulk-assign-documents",
    "label": "Bulk Assign Documents",
    "sourceModule": "activities",
    "ownerModule": "bulk-assignment",
    "actionType": "navigate",
    "navigateTo": "bulk-assignment",
    "openAs": "full-route",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "bulk-assignment",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "export-selection",
    "label": "Export Selection",
    "sourceModule": "activities",
    "ownerModule": "reports",
    "actionType": "export",
    "navigateTo": "reports",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:selection-exported",
    "backendContract": "none",
    "postSuccess": "activities",
    "postCancel": "activities",
    "notes": ""
  },
  {
    "id": "preview-assignment-payload",
    "label": "Preview Assignment Payload",
    "sourceModule": "single-assignment",
    "ownerModule": "single-assignment",
    "actionType": "open-modal",
    "navigateTo": "single-assignment",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "audit:assignment-previewed",
    "backendContract": "none",
    "postSuccess": "single-assignment",
    "postCancel": "single-assignment",
    "notes": ""
  },
  {
    "id": "submit-single-assignment",
    "label": "Submit Single Assignment",
    "sourceModule": "single-assignment",
    "ownerModule": "single-assignment",
    "actionType": "endpoint-action",
    "navigateTo": "orchestrator",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:assigned",
    "backendContract": "SINGLE_ASSIGNMENT",
    "postSuccess": "orchestrator",
    "postCancel": "single-assignment",
    "notes": ""
  },
  {
    "id": "submit-bulk-assignment",
    "label": "Submit Bulk Assignment",
    "sourceModule": "bulk-assignment",
    "ownerModule": "bulk-assignment",
    "actionType": "endpoint-action",
    "navigateTo": "orchestrator",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:bulk-assignment-submitted",
    "backendContract": "BULK_ASSIGNMENT",
    "postSuccess": "orchestrator",
    "postCancel": "bulk-assignment",
    "notes": ""
  },
  {
    "id": "reset-assignment-draft",
    "label": "Reset Assignment Draft",
    "sourceModule": "single-assignment",
    "ownerModule": "single-assignment",
    "actionType": "local-state",
    "navigateTo": "single-assignment",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": true,
    "auditEvent": "audit:assignment-draft-reset",
    "backendContract": "none",
    "postSuccess": "single-assignment",
    "postCancel": "single-assignment",
    "notes": ""
  },
  {
    "id": "fetch-emails",
    "label": "Fetch Emails",
    "sourceModule": "correspondence",
    "ownerModule": "correspondence",
    "actionType": "endpoint-action",
    "navigateTo": "correspondence",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:emails-fetched",
    "backendContract": "SUBSIDIARY_ACTIONS",
    "postSuccess": "correspondence",
    "postCancel": "correspondence",
    "notes": ""
  },
  {
    "id": "open-email-detail",
    "label": "Open Email Detail",
    "sourceModule": "correspondence",
    "ownerModule": "lookup",
    "actionType": "open-detail",
    "navigateTo": "lookup",
    "openAs": "detail-pane",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "lookup",
    "postCancel": "correspondence",
    "notes": ""
  },
  {
    "id": "create-task-from-email",
    "label": "Create Task From Email",
    "sourceModule": "correspondence",
    "ownerModule": "single-assignment",
    "actionType": "navigate",
    "navigateTo": "single-assignment",
    "openAs": "full-route",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "single-assignment",
    "postCancel": "correspondence",
    "notes": ""
  },
  {
    "id": "submit-email-task",
    "label": "Submit Email Task",
    "sourceModule": "single-assignment",
    "ownerModule": "single-assignment",
    "actionType": "endpoint-action",
    "navigateTo": "orchestrator",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:email-task-created",
    "backendContract": "EMAIL_RELATED_TASK",
    "postSuccess": "orchestrator",
    "postCancel": "single-assignment",
    "notes": ""
  },
  {
    "id": "fetch-email-attachments",
    "label": "Fetch Email Attachments",
    "sourceModule": "correspondence",
    "ownerModule": "correspondence",
    "actionType": "endpoint-action",
    "navigateTo": "correspondence",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "audit:email-attachments-fetched",
    "backendContract": "FETCH_EMAIL_ATTACHMENTS",
    "postSuccess": "correspondence",
    "postCancel": "correspondence",
    "notes": ""
  },
  {
    "id": "fetch-tasks",
    "label": "Fetch Tasks",
    "sourceModule": "orchestrator",
    "ownerModule": "orchestrator",
    "actionType": "endpoint-action",
    "navigateTo": "orchestrator",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:tasks-fetched",
    "backendContract": "FETCH_ACTIVITIES",
    "postSuccess": "orchestrator",
    "postCancel": "orchestrator",
    "notes": ""
  },
  {
    "id": "open-task-detail",
    "label": "Open Task Detail",
    "sourceModule": "orchestrator",
    "ownerModule": "orchestrator",
    "actionType": "open-detail",
    "navigateTo": "orchestrator",
    "openAs": "detail-pane",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "orchestrator",
    "postCancel": "orchestrator",
    "notes": ""
  },
  {
    "id": "update-task",
    "label": "Update Task",
    "sourceModule": "orchestrator",
    "ownerModule": "orchestrator",
    "actionType": "governed-action",
    "navigateTo": "orchestrator",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:task-updated",
    "backendContract": "DYNAMIC_ACTIONS.optional",
    "postSuccess": "orchestrator",
    "postCancel": "orchestrator",
    "notes": ""
  },
  {
    "id": "set-reminder",
    "label": "Set Reminder",
    "sourceModule": "orchestrator",
    "ownerModule": "orchestrator",
    "actionType": "governed-action",
    "navigateTo": "orchestrator",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:reminder-set",
    "backendContract": "DYNAMIC_ACTIONS",
    "postSuccess": "orchestrator",
    "postCancel": "orchestrator",
    "notes": ""
  },
  {
    "id": "reassign-task",
    "label": "Reassign Task",
    "sourceModule": "orchestrator",
    "ownerModule": "single-assignment",
    "actionType": "navigate",
    "navigateTo": "single-assignment",
    "openAs": "full-route",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "single-assignment",
    "postCancel": "orchestrator",
    "notes": ""
  },
  {
    "id": "refresh-active-tracking-tab",
    "label": "Refresh Active Tracking Tab",
    "sourceModule": "response-tracking",
    "ownerModule": "response-tracking",
    "actionType": "endpoint-action",
    "navigateTo": "response-tracking",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:tracking-refresh",
    "backendContract": "FETCH_ALL",
    "postSuccess": "response-tracking",
    "postCancel": "response-tracking",
    "notes": ""
  },
  {
    "id": "match-doc-email-pairs",
    "label": "Match Doc Email Pairs",
    "sourceModule": "response-tracking",
    "ownerModule": "response-tracking",
    "actionType": "local-state",
    "navigateTo": "response-tracking",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:matched-pairs-built",
    "backendContract": "none",
    "postSuccess": "response-tracking",
    "postCancel": "response-tracking",
    "notes": ""
  },
  {
    "id": "export-tracking-csv",
    "label": "Export Tracking CSV",
    "sourceModule": "response-tracking",
    "ownerModule": "reports",
    "actionType": "export",
    "navigateTo": "reports",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:tracking-exported",
    "backendContract": "none",
    "postSuccess": "response-tracking",
    "postCancel": "response-tracking",
    "notes": ""
  },
  {
    "id": "open-statistics",
    "label": "Open Statistics",
    "sourceModule": "response-tracking",
    "ownerModule": "statistics",
    "actionType": "navigate",
    "navigateTo": "statistics",
    "openAs": "full-route",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "statistics",
    "postCancel": "response-tracking",
    "notes": ""
  },
  {
    "id": "open-settings",
    "label": "Open Settings",
    "sourceModule": "home",
    "ownerModule": "settings",
    "actionType": "navigate",
    "navigateTo": "settings",
    "openAs": "full-route",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "",
    "backendContract": "",
    "postSuccess": "settings",
    "postCancel": "home",
    "notes": ""
  },
  {
    "id": "copy-endpoints",
    "label": "Copy Endpoints JSON",
    "sourceModule": "settings",
    "ownerModule": "settings",
    "actionType": "local-state",
    "navigateTo": "settings",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:endpoints-copied",
    "backendContract": "none",
    "postSuccess": "settings",
    "postCancel": "settings",
    "notes": ""
  },
  {
    "id": "save-endpoint-override",
    "label": "Save Endpoint Override",
    "sourceModule": "settings",
    "ownerModule": "settings",
    "actionType": "local-state",
    "navigateTo": "settings",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": true,
    "auditEvent": "audit:endpoint-override",
    "backendContract": "none",
    "postSuccess": "settings",
    "postCancel": "settings",
    "notes": ""
  },
  {
    "id": "clear-local-data",
    "label": "Clear Local Data",
    "sourceModule": "settings",
    "ownerModule": "settings",
    "actionType": "local-state",
    "navigateTo": "settings",
    "openAs": "modal",
    "requiresReference": false,
    "requiresConfirmation": true,
    "auditEvent": "audit:local-data-cleared",
    "backendContract": "none",
    "postSuccess": "settings",
    "postCancel": "settings",
    "notes": ""
  },
  {
    "id": "copy-diagnostics-log",
    "label": "Copy Diagnostics Log",
    "sourceModule": "diagnostics",
    "ownerModule": "diagnostics",
    "actionType": "local-state",
    "navigateTo": "diagnostics",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:diagnostics-copied",
    "backendContract": "none",
    "postSuccess": "diagnostics",
    "postCancel": "diagnostics",
    "notes": ""
  },
  {
    "id": "acknowledge-task-deeplink",
    "label": "Acknowledge Task from Deep Link",
    "sourceModule": "acknowledgment",
    "ownerModule": "acknowledgment",
    "actionType": "endpoint-action",
    "navigateTo": "acknowledgment",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:acknowledged",
    "backendContract": "SUBSIDIARY_ACTIONS",
    "postSuccess": "orchestrator",
    "postCancel": "acknowledgment",
    "notes": "Ported from taskack-page-gd deep-link acknowledgement flow."
  },
  {
    "id": "open-contextual-support",
    "label": "Open Contextual Support",
    "sourceModule": "anyModule",
    "ownerModule": "assistant",
    "actionType": "navigate",
    "navigateTo": "assistant",
    "openAs": "drawer",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:support-opened",
    "backendContract": "",
    "postSuccess": "assistant",
    "postCancel": "previous-module",
    "notes": "Contextual support drawer converged from support module."
  },
  {
    "id": "submit-support-request",
    "label": "Submit Support Request",
    "sourceModule": "assistant",
    "ownerModule": "assistant",
    "actionType": "endpoint-action",
    "navigateTo": "assistant",
    "openAs": "modal",
    "requiresReference": false,
    "requiresConfirmation": true,
    "auditEvent": "audit:support-request-submitted",
    "backendContract": "SUBSIDIARY_ACTIONS",
    "postSuccess": "assistant",
    "postCancel": "assistant",
    "notes": "Support request with context bundle."
  },
  {
    "id": "export-ack-receipts",
    "label": "Export Acknowledgement Receipts",
    "sourceModule": "operator-hud",
    "ownerModule": "operator-hud",
    "actionType": "export",
    "navigateTo": "operator-hud",
    "openAs": "same-page",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:receipts-exported",
    "backendContract": "none",
    "postSuccess": "operator-hud",
    "postCancel": "operator-hud",
    "notes": "Receipt ledger JSON/CSV export."
  },
  {
    "id": "open-correspondence-email",
    "label": "Open Correspondence Email Desk",
    "sourceModule": "dispatch",
    "ownerModule": "correspondence-email",
    "actionType": "navigate",
    "navigateTo": "correspondence-email",
    "openAs": "full-route",
    "requiresReference": false,
    "requiresConfirmation": false,
    "auditEvent": "audit:correspondence-email-opened",
    "backendContract": "none",
    "postSuccess": "correspondence-email",
    "postCancel": "dispatch",
    "notes": "Open official correspondence email desk."
  },
  {
    "id": "create-correspondence-email-draft",
    "label": "Create Correspondence Email Draft",
    "sourceModule": "correspondence-email",
    "ownerModule": "correspondence-email",
    "actionType": "local-state",
    "navigateTo": "correspondence-email",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": false,
    "auditEvent": "audit:correspondence-email-draft-created",
    "backendContract": "none",
    "postSuccess": "correspondence-email",
    "postCancel": "correspondence-email",
    "notes": "Creates an official outgoing correspondence email draft."
  },
  {
    "id": "send-correspondence-email",
    "label": "Send Official Correspondence Email",
    "sourceModule": "correspondence-email",
    "ownerModule": "correspondence-email",
    "actionType": "endpoint-action",
    "navigateTo": "correspondence-email",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:correspondence-email-sent",
    "backendContract": "EMAIL",
    "postSuccess": "correspondence-email",
    "postCancel": "correspondence-email",
    "notes": "Sends outward correspondence through configured EMAIL endpoint."
  },
  {
    "id": "archive-correspondence-email",
    "label": "Archive Correspondence Email",
    "sourceModule": "correspondence-email",
    "ownerModule": "correspondence-email",
    "actionType": "governed-action",
    "navigateTo": "correspondence-email",
    "openAs": "same-page",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:correspondence-email-archived",
    "backendContract": "none",
    "postSuccess": "correspondence-email",
    "postCancel": "correspondence-email",
    "notes": "Archives correspondence email record."
  },
  {
    "id": "activity-archive",
    "label": "Archive Activity (UNC)",
    "sourceModule": "activities",
    "ownerModule": "activities",
    "actionType": "governed-action",
    "navigateTo": "activities",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:activity-archived",
    "backendContract": "DYNAMIC_ACTIONS",
    "postSuccess": "activities",
    "postCancel": "activities",
    "notes": "Canvas Activities parity lifecycle routing: routes the activity to the DGOFASTTRACK queue with the UNC Reference_ID formula and the Treated/Assigned source update. This is lifecycle routing, not immutable archive execution — archive execution stays owned by the archive module."
  },
  {
    "id": "activity-siwes",
    "label": "Route Activity to SIWES",
    "sourceModule": "activities",
    "ownerModule": "activities",
    "actionType": "governed-action",
    "navigateTo": "activities",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:activity-siwes-routed",
    "backendContract": "DYNAMIC_ACTIONS",
    "postSuccess": "activities",
    "postCancel": "activities",
    "notes": "Canvas Activities parity lifecycle routing: routes the activity to the DGOFASTTRACK queue under Internships (SIWES). This is lifecycle routing, not immutable archive execution — archive execution stays owned by the archive module."
  },
  {
    "id": "activity-nysc",
    "label": "Route Activity to NYSC",
    "sourceModule": "activities",
    "ownerModule": "activities",
    "actionType": "governed-action",
    "navigateTo": "activities",
    "openAs": "modal",
    "requiresReference": true,
    "requiresConfirmation": true,
    "auditEvent": "audit:activity-nysc-routed",
    "backendContract": "DYNAMIC_ACTIONS",
    "postSuccess": "activities",
    "postCancel": "activities",
    "notes": "Canvas Activities parity lifecycle routing: routes the activity to the DGOFASTTRACK queue under Internships (NYSC). This is lifecycle routing, not immutable archive execution — archive execution stays owned by the archive module."
  }
]
});
export const ActionRouteIndex = Object.freeze(Object.fromEntries(ActionRouting.actions.map(a=>[a.id,a])));
export function actionRoute(id){ return ActionRouteIndex[id] || null; }
