import { escapeHtml as esc, statusClass, sourceClass, priorityClass, safeAttr } from './design-system-adapter.js';

const attrs = obj => Object.entries(obj||{}).filter(([,v])=>v!==undefined&&v!==null&&v!==false).map(([k,v])=>v===true?`${k}`:`${k}="${esc(v)}"`).join(' ');
export function Button({label='', variant='secondary', size='md', icon='', type='button', attrs:extra={}, action='', disabled=false}={}){ return `<button type="${esc(type)}" class="dgo-btn dgo-btn--${esc(variant)} dgo-btn--${esc(size)}" ${action?`data-action="${esc(action)}"`:''} ${disabled?'disabled aria-disabled="true"':''} ${attrs(extra)}>${icon?`<span class="dgo-btn__icon">${icon}</span>`:''}<span>${esc(label)}</span></button>`; }
export function IconButton({label='', icon='', variant='ghost', action='', attrs:extra={}}={}){ return `<button type="button" class="dgo-iconbtn dgo-iconbtn--${esc(variant)}" aria-label="${esc(label)}" title="${esc(label)}" ${action?`data-action="${esc(action)}"`:''} ${attrs(extra)}>${icon||'<span aria-hidden="true">•</span>'}</button>`; }
export function Card({title='', eyebrow='', body='', footer='', tone='', attrs:extra={}}={}){ return `<section class="dgo-card ${tone?`dgo-card--${esc(tone)}`:''}" ${attrs(extra)}>${eyebrow?`<div class="dgo-card__eyebrow">${esc(eyebrow)}</div>`:''}${title?`<h3 class="dgo-card__title">${esc(title)}</h3>`:''}${body?`<div class="dgo-card__body">${body}</div>`:''}${footer?`<div class="dgo-card__footer">${footer}</div>`:''}</section>`; }
export function KpiCard({label='', value='', note='', tone='neutral', icon=''}={}){ return `<article class="dgo-kpi-card dgo-kpi-card--${esc(tone)}"><div class="dgo-kpi-card__top"><span>${esc(label)}</span>${icon?`<span aria-hidden="true">${icon}</span>`:''}</div><strong>${esc(value)}</strong>${note?`<small>${esc(note)}</small>`:''}</article>`; }
export function Pipeline(items=[]){ return `<ol class="dgo-pipeline" aria-label="Lifecycle pipeline">${items.map((x,i)=>`<li class="dgo-pipeline__item"><span class="dgo-pipeline__n">${esc(x.n ?? x.value ?? 0)}</span><span class="dgo-pipeline__label">${esc(x.label ?? x.phase ?? `Step ${i+1}`)}</span>${x.note?`<small>${esc(x.note)}</small>`:''}</li>`).join('')}</ol>`; }
export function StatusPill(status, options={}){ return `<span class="${statusClass(status)}" ${attrs(options.attrs)}>${esc(options.label||status||'Status')}</span>`; }
export function SourceBadge(sourceId, options={}){ return `<span class="${sourceClass(sourceId)}" ${attrs(options.attrs)}>${esc(options.label||sourceId||'Unknown source')}</span>`; }
export function PriorityBadge(priority, options={}){ return `<span class="${priorityClass(priority)}" ${attrs(options.attrs)}>${esc(options.label||priority||'Normal')}</span>`; }
export function FormField({id='', label='', hint='', control='', required=false}={}){ return `<label class="dgo-field" ${id?`for="${esc(id)}"`:''}><span class="dgo-field__label">${esc(label)}${required?' <b aria-hidden="true">*</b>':''}</span>${control}${hint?`<small class="dgo-field__hint">${esc(hint)}</small>`:''}</label>`; }
export function TextInput({id='', name='', value='', placeholder='', readonly=false, required=false}={}){ return `<input class="dgo-input" id="${esc(id)}" name="${esc(name||id)}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${readonly?'readonly':''} ${required?'required':''}>`; }
export function SelectInput({id='', name='', value='', options=[]}={}){ return `<select class="dgo-select" id="${esc(id)}" name="${esc(name||id)}">${options.map(o=>{const val=typeof o==='string'?o:o.value,label=typeof o==='string'?o:o.label;return `<option value="${esc(val)}" ${String(val)===String(value)?'selected':''}>${esc(label)}</option>`}).join('')}</select>`; }
export function TextArea({id='', name='', value='', placeholder='', rows=3}={}){ return `<textarea class="dgo-textarea" id="${esc(id)}" name="${esc(name||id)}" rows="${esc(rows)}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`; }
export function Table({columns=[], rows=[], rowAttrs=()=>''}={}){ if(!rows.length) return EmptyState({title:'No records', body:'Nothing to show for the current filter.'}); return `<div class="dgo-table-scroll"><table class="dgo-table"><thead><tr>${columns.map(c=>`<th scope="col">${esc(c.label||c.key)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr ${rowAttrs(r)}>${columns.map(c=>`<td data-label="${esc(c.label||c.key)}">${c.render?c.render(r):esc(r[c.key]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
export function RecordRow({reference='', title='', meta='', status='', source='', href='', attrs:extra={}}={}){ const tag=href?'a':'div'; return `<${tag} class="dgo-record-row" ${href?`href="${esc(href)}"`:''} ${attrs(extra)}><span class="dgo-record-row__ref">${esc(reference)}</span><span class="dgo-record-row__main"><strong>${esc(title)}</strong><small>${esc(meta)}</small></span><span class="dgo-record-row__badges">${source?SourceBadge(source):''}${status?StatusPill(status):''}</span></${tag}>`; }
export function TaskCard(task={}){ return Card({title:task.title||task.subject||task.referenceId||'Task', eyebrow:task.referenceId||task.ref||'Task', body:`<p>${esc(task.summary||task.description||'No summary provided.')}</p><div class="dgo-chip-row">${StatusPill(task.status||task.assignmentStatus||'Pending')}${PriorityBadge(task.priority||'Normal')}${task.owner||task.assignedTo?`<span class="dgo-chip">${esc(task.owner||task.assignedTo)}</span>`:''}</div>`, footer:task.due?`<small>Due ${esc(task.due)}</small>`:''}); }
export function MinuteTrail(items=[]){ return `<ol class="dgo-minute-trail">${(items||[]).map(i=>`<li><time>${esc(i.at||i.date||'')}</time><strong>${esc(i.by||i.actor||'Registry')}</strong><p>${esc(i.text||i.note||i.body||'')}</p></li>`).join('')||'<li><p>No minute trail recorded.</p></li>'}</ol>`; }
export function MasterDetail({list='', detail='', view='list'}={}){ return `<div class="dgo-master-detail" data-md="${esc(view)}"><section class="dgo-master-detail__list">${list}</section><section class="dgo-master-detail__detail">${detail}</section></div>`; }
export function Dialog({title='', body='', actions='', id='dgo-dialog'}={}){ return `<div class="dgo-dialog-backdrop" data-dialog="${esc(id)}"><section class="dgo-dialog" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><h2>${esc(title)}</h2><button type="button" class="dgo-iconbtn" data-dialog-close aria-label="Close dialog">×</button></header><div class="dgo-dialog__body">${body}</div><footer>${actions}</footer></section></div>`; }
export function ToastHost(){ return `<div class="dgo-toast-host" role="status" aria-live="polite" data-toast-host></div>`; }
export function EmptyState({title='Nothing here yet', body='Records will appear here when available.', action=''}={}){ return `<section class="dgo-empty"><h2>${esc(title)}</h2><p>${esc(body)}</p>${action}</section>`; }
export function HealthCard({label='', value='', tone='success', note=''}={}){ return KpiCard({label,value,note,tone}); }
export function ActionBar({actions=[]}={}){ return `<div class="dgo-actionbar">${actions.join('')}</div>`; }
export function CommandPalette(){ return `<div class="dgo-cmdk" data-command-palette hidden><div class="dgo-cmdk__backdrop" data-command-close></div><section class="dgo-cmdk__dialog" role="dialog" aria-modal="true" aria-label="Command palette"><div class="dgo-cmdk__search"><input data-command-input placeholder="Search references, tasks, people, workspaces..." aria-label="Command search"></div><div class="dgo-cmdk__list" role="listbox" data-command-results></div><footer class="dgo-cmdk__footer">Enter to open. Esc to close.</footer></section></div>`; }
export function PersonaSwitcher({name='', role='', avatar='' }={}){ return `<button type="button" class="dgo-persona" data-persona-menu aria-haspopup="menu" aria-expanded="false">${avatar?`<span>${avatar}</span>`:''}<span><b>${esc(name)}</b><small>${esc(role)}</small></span></button>`; }
export function WorkspaceHeader({title='', subtitle='', eyebrow='DGO DIGITAL OPS'}={}){ return `<header class="dgo-workspace-header"><div><div class="dgo-overline">${esc(eyebrow)}</div><h1>${esc(title)}</h1>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div></header>`; }


// Figma UI/UX implementation factories - zero-build, vanilla HTML strings
export function StatBand(items=[]){ return `<section class="dgo-stat-band" aria-label="Workspace metrics">${items.map(x=>`<article class="dgo-stat dgo-stat--${esc(x.tone||'neutral')}"><span class="dgo-stat__label">${esc(x.label||'Metric')}</span><strong class="dgo-stat__value">${esc(x.value??'0')}</strong>${x.note?`<small class="dgo-stat__note">${esc(x.note)}</small>`:''}</article>`).join('')}</section>`; }
export function Toolbar({title='', controls='', actions='', attrs:extra={}}={}){ return `<section class="dgo-toolbar" ${attrs(extra)}>${title?`<strong>${esc(title)}</strong>`:''}<div class="dgo-toolbar__controls">${controls}</div><div class="dgo-toolbar__actions">${actions}</div></section>`; }
export function FilterBar({filters='', actions='', attrs:extra={}}={}){ return `<section class="dgo-filterbar" ${attrs(extra)}>${filters}<span class="dgo-filterbar__spacer"></span>${actions}</section>`; }
export function DetailPane({eyebrow='', title='', meta='', status='', body='', actions='', attrs:extra={}}={}){ return `<section class="dgo-detail-pane" ${attrs(extra)}>${eyebrow?`<div class="dgo-overline">${esc(eyebrow)}</div>`:''}${status?`<div class="dgo-chip-row">${status}</div>`:''}${title?`<h2>${esc(title)}</h2>`:''}${meta?`<p class="dgo-muted">${esc(meta)}</p>`:''}<div class="dgo-detail-pane__body">${body}</div>${actions?`<footer class="dgo-actionbar">${actions}</footer>`:''}</section>`; }
export function Drawer({id='dgo-drawer', title='', body='', actions='', hidden=true}={}){ return `<aside class="dgo-drawer" data-drawer="${esc(id)}" ${hidden?'hidden':''}><div data-drawer-close></div><section class="dgo-drawer__panel" role="dialog" aria-modal="true" aria-label="${esc(title||'Drawer')}"><header class="dgo-drawer__header"><h2>${esc(title)}</h2><button type="button" class="dgo-iconbtn" data-drawer-close aria-label="Close drawer">×</button></header><div class="dgo-drawer__body">${body}</div>${actions?`<footer class="dgo-actionbar">${actions}</footer>`:''}</section></aside>`; }
export function Tabs({items=[], selected='', attr='data-tab'}={}){ return `<div class="dgo-tabs" role="tablist">${items.map(x=>`<button type="button" class="dgo-tab ${String(x.value)===String(selected)?'active':''}" role="tab" aria-selected="${String(x.value)===String(selected)?'true':'false'}" ${attr}="${esc(x.value)}">${esc(x.label||x.value)}</button>`).join('')}</div>`; }
export function Pagination({page=1,total=1,attr='data-page'}={}){ const p=Math.max(1,Number(page)||1), t=Math.max(1,Number(total)||1); return `<nav class="dgo-pagination" aria-label="Pagination"><button class="btn ghost" ${attr}="${Math.max(1,p-1)}" ${p<=1?'disabled':''}>Previous</button><span class="chip">Page ${p} of ${t}</span><button class="btn ghost" ${attr}="${Math.min(t,p+1)}" ${p>=t?'disabled':''}>Next</button></nav>`; }
export function Skeleton({lines=3}={}){ return `<div class="dgo-skeleton-set" aria-hidden="true">${Array.from({length:lines}).map((_,i)=>`<div class="dgo-skeleton" style="width:${i%3===0?'96':i%3===1?'78':'88'}%;height:${i===0?'22':'16'}px;margin:8px 0"></div>`).join('')}</div>`; }
export function Alert({title='', body='', tone='info'}={}){ return `<section class="dgo-alert dgo-alert--${esc(tone)}" role="status"><strong>${esc(title)}</strong>${body?`<p>${esc(body)}</p>`:''}</section>`; }
export function ConfirmDialog({title='', body='', confirmText='Confirm', cancelText='Cancel'}={}){ return Dialog({title, body, actions:`${Button({label:cancelText,variant:'secondary',attrs:{'data-dialog-cancel':true}})}${Button({label:confirmText,variant:'primary',attrs:{'data-dialog-confirm':true}})}`}); }
/* srcdoc content is always live HTML: esc() protects the attribute boundary, but the parser
   decodes the entities and the iframe then parses the result as a document. sandbox="" is
   therefore the only control that stops scripts running, and it must not be omitted — the
   sibling frames in modules/correspondence-email.js already use it. */
export function EmailPreviewFrame({html='', title='Email preview'}={}){ return `<iframe class="dgo-email-preview email-frame-preview" sandbox="" title="${esc(title)}" srcdoc="${esc(html)}"></iframe>`; }
